name: CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
           
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test --configuration Release --no-build
      
    - name: Publish
      run: dotnet publish -c Release -o publish
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: publish
        path: ./publish
